### ISSUE TITLE
Меню inline

### ISSUE THREAD

**Issue by Hade5** [Ren4ik1988/CSharpEducationBot#12]
Сделать тестовое меню inline.

- Составить  примерное будущее меню
- Постараться выделить код в отдельный класс

**Comment by Hade5** [comment]
- Класс в котором находятся обработчики колбеков должен быть запущен при старте бота, иначе старое меню не будет работать.
- ошибка при попытке повтороно изменить уже существующее меню
- при изменении меню не забывать высылать новую клавиатуру

**Comment by Hade5** [comment]
полный список выводить по 5-7 записей в формате
название год уровень ссылка

**Comment by Hade5** [comment]
когда выдавать новое меню? т.е. мы вывели список ресурсов, он скачал допустим 2 файла и решил вернуться в главное меню. Пользователю надо будет скролить назад или делать новое после  нажатия главное меню.

**Comment by Ren4ik1988** [comment]
Необязательно скролить, просто можно оставить команду активную всегда, для возможности выхода в главное меню , например \gohome

**Comment by Hade5** [comment]
Шаги по меню надо хранить для каждого пользователя отдельно, чтобы знать куда возвращаться. Возможно хранить не только шаги, но и сейв его состояния, до возврата пользователя в главное меню.
