### ISSUE TITLE
Метод init()

### ISSUE THREAD

**Issue by Hade5** [Ren4ik1988/CSharpEducationBot#7]
- реализовать сам метод
- собрать в нем все подставке проверки
- упорядочить их по приоритету
- обработать исключения

**Comment by Ren4ik1988** [comment]
Запушил в ветку Fix#3Ren

**Comment by Ren4ik1988** [comment]
Метод init() реализовал, для произведения проверок создал два класса  GetToken и ConnectionTest с обработками исключений.
